typography_spectrum: 0.81433
color:
  brandColors:
    - '#ffffff'
    - '#95a0ac'
    - '#c9c7b6'
    - '#3e3c35'
    - '#0c0e0f'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: iamhybrid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: iamhybrid
purpose: []
