name: iamhybrid
favicon: null
layout_spectrum: 0.3785864352248609
typography_spectrum: 0.9459989629685879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19363047485239804
  lightness: 0.2067624486517161
  saturation: 0.8746249803807586
  rhythmicContrast: 0.4289785616565496
purpose: []
